[db]
path = "db/all_dbs/"
bannerdb = "banner-db.db"
cheatsheetsdb = "cheatsheets-db-v5.db"
emojidb = "emoji-db-v5.db"
ipmdb = "ipm-db-v6.db"
manpagesdb = "man-pages-db-v5.db"
mcpdb = "mcp-db-v6.db"
pngiconsdb = "png-icons-db-v5.db"
svgiconsdb = "svg-icons-db-v5.db"
tldrdb = "tldr-db-v5.db"
